In [10]:
path = "./archive/Face Mask Dataset"

In [40]:
import glob
import re
import os
import pandas as pd

train_withmask = pd.DataFrame(glob.glob('./archive/Face Mask Dataset/Train/WithMask/*.png', recursive=True))
train_withmask['mask'] = 'mask'
train_withoutmask = pd.DataFrame(glob.glob('./archive/Face Mask Dataset/Train/WithoutMask/*.png', recursive=True))
train_withoutmask['mask'] = 'unmask'

In [41]:
train_withmask

                                                      0  mask
0     ./archive/Face Mask Dataset/Train/WithMask\10.png  mask
1     ./archive/Face Mask Dataset/Train/WithMask\100...  mask
2     ./archive/Face Mask Dataset/Train/WithMask\100...  mask
3     ./archive/Face Mask Dataset/Train/WithMask\100...  mask
4     ./archive/Face Mask Dataset/Train/WithMask\100...  mask
...                                                 ...   ...
4995  ./archive/Face Mask Dataset/Train/WithMask\Aug...  mask
4996  ./archive/Face Mask Dataset/Train/WithMask\Aug...  mask
4997  ./archive/Face Mask Dataset/Train/WithMask\Aug...  mask
4998  ./archive/Face Mask Dataset/Train/WithMask\Aug...  mask
4999  ./archive/Face Mask Dataset/Train/WithMask\Aug...  mask

[5000 rows x 2 columns]

In [42]:
csv_data = pd.concat([train_withmask, train_withoutmask], axis=0).reset_index(drop=True)

In [43]:
csv_data

                                                      0    mask
0     ./archive/Face Mask Dataset/Train/WithMask\10.png    mask
1     ./archive/Face Mask Dataset/Train/WithMask\100...    mask
2     ./archive/Face Mask Dataset/Train/WithMask\100...    mask
3     ./archive/Face Mask Dataset/Train/WithMask\100...    mask
4     ./archive/Face Mask Dataset/Train/WithMask\100...    mask
...                                                 ...     ...
9995  ./archive/Face Mask Dataset/Train/WithoutMask\...  unmask
9996  ./archive/Face Mask Dataset/Train/WithoutMask\...  unmask
9997  ./archive/Face Mask Dataset/Train/WithoutMask\...  unmask
9998  ./archive/Face Mask Dataset/Train/WithoutMask\...  unmask
9999  ./archive/Face Mask Dataset/Train/WithoutMask\...  unmask

[10000 rows x 2 columns]